'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'zh' | 'ur';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  locale: Language; // Alias for language
  setLocale: (lang: Language) => void; // Alias for setLanguage
  t: (key: string, params?: Record<string, string>) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.factories': 'Factories',
    'nav.products': 'Products',
    'nav.rfq': 'Submit RFQ',
    'nav.dashboard': 'Dashboard',
    'nav.signin': 'Sign In',
    'nav.login': 'Login',
    'nav.messages': 'Messages',
    'nav.settings': 'Settings',
    'nav.suppliers': 'Saved Suppliers',
    'nav.profile': 'Factory Profile',
    'nav.logout': 'Logout',
    'nav.live': 'Live Production',
    'nav.search_placeholder': 'Search products or factories...',
    'hero.title': 'The Digital Gateway to Gulf Manufacturing',
    'hero.subtitle': 'Connect directly with verified factories in Saudi Arabia and the GCC. Streamline your sourcing with AI-powered matching.',
    'hero.cta.start': 'Start Sourcing',
    'hero.cta.factory': 'List Your Factory',
    'hero.cta.join': 'Join as Factory',
    'hero.cta.rfq': 'Submit RFQ',
    'dashboard.welcome': 'Welcome back',
    'dashboard.factory': 'Factory Dashboard',
    'dashboard.buyer': 'Buyer Dashboard',
    'dashboard.stats.total_products': 'Total Products',
    'dashboard.stats.total_quotes': 'Total Quotes',
    'dashboard.stats.profile_views': 'Profile Views',
    'dashboard.stats.unread_messages': 'Unread Messages',
    'dashboard.stats.active_rfqs': 'Active RFQs',
    'dashboard.stats.total_orders': 'Total Orders',
    'dashboard.stats.saved_factories': 'Saved Factories',
    'dashboard.ai_insights': 'AI Sourcing Insights',
    'dashboard.ai_desc': 'Based on current market trends, there is a 15% increase in demand for sustainable packaging in the Gulf region.',
    'dashboard.ai_insights_title': 'Optimize your supply chain with GulfFactory AI',
    'dashboard.ai_insights_subtitle': 'AI Sourcing Insights',
    'dashboard.ai_insights_description': 'Based on your recent activity, we\'ve identified 3 new verified factories in the Eastern Province that match your sourcing criteria for industrial plastics.',
    'dashboard.ai_insights_button': 'View AI Recommendations',
    'dashboard.performance': 'Performance Overview',
    'dashboard.performance_desc': 'Analytics for the last 30 days',
    'dashboard.last_7_days': 'Last 7 days',
    'dashboard.last_30_days': 'Last 30 days',
    'dashboard.last_12_months': 'Last 12 months',
    'dashboard.views': 'views',
    'dashboard.recent_activity': 'Recent Activity',
    'dashboard.no_activity': 'No recent activity',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.action.new_product': 'Add New Product',
    'dashboard.action.view_rfqs': 'View RFQs',
    'dashboard.action.live_stream': 'Go Live',
    'activity.new_rfq': 'New RFQ received',
    'activity.new_rfq_desc': 'Aluminum Parts for Automotive',
    'activity.new_message': 'New Message',
    'activity.new_message_desc': 'From Saudi Steel Co.',
    'activity.order_completed': 'Order Completed',
    'activity.order_completed_desc': 'Order #ORD-742',
    
    'profile.title': 'Factory Profile',
    'profile.subtitle': 'Manage your factory branding and information.',
    'profile.save': 'Save Changes',
    'profile.factory_name': 'Factory Name',
    'profile.description': 'Factory Description',
    'profile.location': 'Location',
    'profile.category': 'Primary Category',
    'profile.branding': 'Branding',
    'profile.logo': 'Factory Logo',
    'profile.banner': 'Profile Banner',
    
    'products.title': 'Product Management',
    'products.subtitle': 'Manage your product catalog and visibility.',
    'products.add': 'Add Product',
    'products.search': 'Search products...',
    'products.name': 'Product Name',
    'products.category': 'Category',
    'products.price': 'Price',
    'products.status': 'Status',
    'products.actions': 'Actions',
    'products.empty': 'No products found.',
    
    'products.new.title': 'Add New Product',
    'products.new.subtitle': 'List a new product on the GulfFactory marketplace.',
    'products.new.basic_info': 'Basic Information',
    'products.new.media': 'Product Media',
    'products.new.description': 'Description',
    'products.new.min_order': 'Minimum Order Quantity',
    'products.new.price_range': 'Price Range',
    'products.new.images': 'Product Images',
    'products.new.video': 'Product Video',
    'products.new.submit': 'Create Product',
    'products.new.success': 'Product created successfully!',

    'live.title': 'Live Production',
    'live.subtitle': 'Stream your factory floor live to build trust with buyers.',
    'live.start': 'Go Live Now',
    'live.stop': 'End Stream',
    'live.ready': 'Ready to broadcast?',
    'live.ready_desc': 'Showcase your quality standards and production capacity in real-time.',
    'live.chat': 'Live Chat',
    'live.no_messages': 'No messages yet. Start the conversation!',
    'live.type_message': 'Type a message...',
    'live.say_something': 'Say something...',
    'live.ask_factory': 'Ask the factory directly...',
    'live.host': 'Host',
    'live.factory': 'Factory',
    'live.send': 'Send',
    'live.security': 'Security',
    'live.encrypted': 'End-to-End',
    'live.latency': 'Latency',
    'live.ultra_low': 'Ultra Low',
    'live.quality': 'Quality',
    'live.switch_camera': 'Switch Camera',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred.',
    'common.success': 'Success!',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.view_all': 'View All',
    'rfq.new_title': 'Submit New RFQ',
    'rfq.new_subtitle': 'Provide detailed requirements to get accurate quotes.',
    'rfq.product_name': 'Product Name / RFQ Title',
    'rfq.category': 'Category',
    'rfq.quantity': 'Required Quantity',
    'rfq.target_price': 'Target Price per Unit (USD)',
    'rfq.description': 'Detailed Specifications',
    'rfq.attachments': 'Attachments',
    'rfq.submit': 'Submit RFQ',
    'rfq.submitting': 'Submitting...',
    'rfq.success': 'RFQ Submitted Successfully!',
    'rfq.success_desc': 'Your Request for Quotation has been sent to our network of verified factories.',
    'rfq.received_title': 'Received RFQs',
    'rfq.my_rfqs': 'My RFQs',
    'rfq.manage_desc': 'Manage requests for quotations from buyers.',
    'rfq.track_desc': 'Track your requests for quotations.',
    'rfq.ai_help': 'AI Assistant',
    'rfq.ai_write': 'Write for me',
    'rfq.ai_improve': 'Improve phrasing',
    'rfq.ai_suggest_specs': 'Suggest specs',
    'rfq.step_1': 'Product Info',
    'rfq.step_2': 'Quantity & Price',
    'rfq.step_3': 'Details & Files',
    'rfq.next': 'Next Step',
    'rfq.prev': 'Previous',
    'rfq.draft_saved': 'Draft saved',
    'rfq.new_rfq': 'New RFQ',
    'rfq.all': 'All',
    'rfq.pending': 'Pending',
    'rfq.quoted': 'Quoted',
    'rfq.accepted': 'Accepted',
    'rfq.rejected': 'Rejected',
    'rfq.search_placeholder': 'Search RFQs...',
    'rfq.results': 'Results',
    'rfq.loading': 'Loading RFQs...',
    'rfq.details': 'RFQ Details',
    'rfq.status': 'Status',
    'rfq.date': 'Date',
    'rfq.no_rfqs': 'No RFQs found',
    'rfq.no_received_desc': "You haven't received any RFQs yet.",
    'rfq.no_submitted_desc': "You haven't submitted any RFQs yet.",
    'rfq.submit_first': 'Submit Your First RFQ',
    'suppliers.title': 'Saved Suppliers',
    'suppliers.subtitle': 'Manage your favorite factories and quick contacts.',
    'suppliers.find_more': 'Find More',
    'suppliers.search_placeholder': 'Search saved suppliers...',
    'suppliers.verified': 'Verified',
    'suppliers.profile': 'Profile',
    'suppliers.message': 'Message',
    'suppliers.no_suppliers': 'No saved suppliers',
    'suppliers.no_suppliers_desc': "You haven't saved any factories to your list yet.",
    'suppliers.browse': 'Browse Factories',
    'messages.title': 'Messages',
    'messages.search': 'Search conversations...',
    'messages.empty': 'No messages yet',
    'messages.type_placeholder': 'Type your message...',
    'messages.select_chat': 'Select a Conversation',
    'messages.select_chat_desc': 'Connect with manufacturers and buyers to discuss requirements, quotes, and delivery timelines.',
    'messages.online': 'Online',
    'messages.you': 'You',
    'messages.suggested_1': 'Can you send more details?',
    'messages.suggested_2': 'What is the lead time?',
    'messages.suggested_3': 'I am interested in a quote.',
    'messages.upload_media': 'Upload Media',
    'messages.drop_file': 'Drop image or video here',
    'messages.sent_image': 'Sent an image',
    'messages.sent_video': 'Sent a video',
    'messages.attachment': 'Attachment',
    'messages.translate': 'Translate',
    'messages.summary': 'AI Summary',
    'messages.suggested': 'Suggested Replies',
    'messages.convert_to_rfq': 'Convert to RFQ',
    'messages.last_seen': 'Last seen',
    'admin.users_title': 'User Management',
    'admin.users_subtitle': 'Manage platform users, roles, and permissions.',
    'admin.search_users': 'Search users by name or email...',
    'admin.no_users': 'No users found',
    'admin.no_users_desc': 'There are currently no users in the database.',
    'admin.user': 'User',
    'admin.role': 'Role',
    'admin.joined': 'Joined',
    'admin.actions': 'Actions',
    'admin.confirm_role': 'Are you sure you want to change this user\'s role to {role}?',
    'admin.confirm_delete': 'Are you sure you want to delete this user? This action cannot be undone.',
    'admin.delete_success': 'User deleted successfully.',
    'admin.delete_error': 'Failed to delete user.',
    'admin.role_error': 'Failed to update user role.',
    'admin.buyer': 'Buyer',
    'admin.factory': 'Factory',
    'admin.admin': 'Admin',
    'admin.factories_title': 'Factory Management',
    'admin.factories_subtitle': 'Manage factory profiles and verification status.',
    'admin.search_factories': 'Search factories by name or email...',
    'admin.no_factories': 'No factories found',
    'admin.no_factories_desc': 'There are currently no factories registered on the platform.',
    'admin.factory_name': 'Factory',
    'admin.location': 'Location',
    'admin.status': 'Status',
    'admin.verified': 'Verified',
    'admin.pending': 'Pending Verification',
    'admin.confirm_verify': 'Are you sure you want to verify this factory?',
    'admin.confirm_revoke': 'Are you sure you want to revoke verification for this factory?',
    'admin.verify_error': 'Failed to update factory verification status.',
    'admin.delete_factory_error': 'Failed to delete factory.',
    'admin.confirm_delete_factory': 'Are you sure you want to delete this factory? This action cannot be undone.',
    'admin.products_title': 'Product Management',
    'admin.products_subtitle': 'Monitor and manage all products listed on the platform.',
    'admin.search_products': 'Search products by name or category...',
    'admin.no_products': 'No products found',
    'admin.no_products_desc': 'There are currently no products listed on the platform.',
    'admin.product': 'Product',
    'admin.factory_id': 'Factory ID',
    'admin.price_moq': 'Price / MOQ',
    'admin.on_request': 'On Request',
    'admin.confirm_delete_product': 'Are you sure you want to delete this product? This action cannot be undone.',
    'admin.delete_product_error': 'Failed to delete product.',
    'admin.rfqs_title': 'RFQ Management',
    'admin.rfqs_subtitle': 'Monitor all Requests for Quotation across the platform.',
    'admin.search_rfqs': 'Search RFQs by title, ID, or category...',
    'admin.no_rfqs': 'No RFQs found',
    'admin.no_rfqs_desc': 'There are currently no RFQs on the platform.',
    'admin.rfq_details': 'RFQ Details',
    'admin.buyer_factory': 'Buyer / Factory',
    'admin.date': 'Date',
    'admin.confirm_delete_rfq': 'Are you sure you want to delete this RFQ? This action cannot be undone.',
    'admin.delete_rfq_error': 'Failed to delete RFQ.',
    'rfq.not_found': 'RFQ Not Found',
    'rfq.back_to_rfqs': 'Back to RFQs',
    'rfq.requirements': 'Detailed Requirements',
    'rfq.attachment': 'Attachment',
    'rfq.summary': 'Request Summary',
    'rfq.quantity_required': 'Quantity Required',
    'rfq.current_status': 'Current Status',
    'rfq.quotations_received': 'Quotations Received',
    'rfq.quote_from_factory': 'Quote from Factory',
    'rfq.per_unit': 'per unit',
    'rfq.lead_time': 'Lead Time',
    'rfq.additional_notes': 'Additional Notes',
    'rfq.accept_quote': 'Accept Quote',
    'rfq.reject': 'Reject',
    'rfq.no_quotes': 'No quotes received yet',
    'rfq.no_quotes_desc': 'Quotes will appear here once submitted by factories.',
    'rfq.submit_quote': 'Submit a Quote',
    'rfq.price_per_unit': 'Price per Unit (USD) *',
    'rfq.estimated_lead_time': 'Estimated Lead Time *',
    'rfq.quote_success': 'Quote submitted successfully!',
    'rfq.quote_error': 'Failed to submit quote.',
    'rfq.confirm_action': 'Are you sure you want to {action} this quote?',
    'rfq.action_error': 'Failed to {action} quote.',
    'rfq.units': 'UNITS',
    'rfq.not_specified': 'Not specified',
    'rfq.no_notes': 'No additional notes.',
    'rfq.price_placeholder': 'e.g., 45.00',
    'rfq.lead_time_placeholder': 'e.g., 14-21 days',
    'rfq.notes_placeholder': 'Include shipping terms, validity of quote, etc.',
    'dashboard.loading': 'Loading...',
    'dashboard.signin_required': 'Please sign in to access your dashboard',
    'dashboard.support': 'Support',
    'dashboard.support_desc': 'Need help with your factory profile?',
    'dashboard.contact_agent': 'Contact Agent',
    'admin.users': 'Admin Users',
    'admin.factories': 'Admin Factories',
    'admin.products': 'Admin Products',
    'admin.rfqs': 'Admin RFQs',
    'hero.badge': 'The Gulf’s Premier Industrial Marketplace',
    'hero.title1': 'Direct Sourcing from',
    'hero.title2': 'Verified Factories',
    'stats.factories': 'Verified Factories',
    'stats.products': 'Industrial Products',
    'stats.volume': 'Trade Volume',
    'stats.countries': 'Countries Reached',
    'features.title': 'Built for Global B2B Trade',
    'features.subtitle': 'Streamline your procurement process with tools designed specifically for industrial sourcing and wholesale trade.',
    'features.v_suppliers': 'Verified Suppliers',
    'features.v_suppliers_desc': 'Every factory undergoes a strict verification process. View certifications, production capacity, and export readiness before engaging.',
    'features.export_ready': 'Export Ready',
    'features.export_ready_desc': 'Filter suppliers by Incoterms (EXW, FOB, CIF, DDP) and find partners experienced in international shipping and customs.',
    'features.bulk_rfq': 'Bulk RFQ Workflows',
    'features.bulk_rfq_desc': 'Submit one detailed Request for Quotation and receive competitive bids from multiple qualified manufacturers simultaneously.',
    'categories.title': 'Industrial Categories',
    'categories.subtitle': 'Browse products from top manufacturing sectors.',
    'categories.view_all': 'View All Categories',
    'cta.ready': 'Ready to scale your sourcing?',
    'cta.desc': 'Join thousands of buyers and factories already trading on GulfFactory Market.',
    'cta.post_rfq': 'Post an RFQ Now',
    'cta.create_account': 'Create Buyer Account',
    'cat.construction': 'Construction Materials',
    'cat.petrochemicals': 'Petrochemicals',
    'cat.machinery': 'Machinery & Equipment',
    'cat.plastics': 'Plastics & Packaging',
    'cat.metals': 'Metals & Alloys',
    'cat.electrical': 'Electrical Components',
    'cat.food': 'Food Processing',
    'cat.textiles': 'Textiles',
    'rfq.view_my': 'View My RFQs',
    'rfq.title_placeholder': 'e.g., 5000 units of custom HDPE packaging',
    'rfq.category.construction': 'Construction Materials',
    'rfq.category.petrochemicals': 'Petrochemicals',
    'rfq.category.machinery': 'Machinery & Equipment',
    'rfq.category.plastics': 'Plastics & Packaging',
    'rfq.category.metals': 'Metals & Alloys',
    'rfq.category.other': 'Other',
    'rfq.quantity_placeholder': 'Enter required quantity',
    'rfq.desc_placeholder': 'Provide details like material, dimensions, certifications required, and delivery timeline...',
    'product.success_title': 'Product Added Successfully!',
    'product.success_desc': 'Your product is now listed on the marketplace and visible to buyers worldwide.',
    'product.add_another': 'Add Another',
    'product.view_catalog': 'View Catalog',
    'product.add_subtitle': 'Showcase your industrial products to verified buyers across the Gulf.',
    'product.name_placeholder': 'e.g., Industrial Grade HDPE Resin',
    'product.moq_placeholder': 'e.g., 1000',
    'product.generating': 'Generating...',
    'product.generate_ai': 'Generate with AI',
    'product.desc_placeholder': 'Describe your product specifications, quality standards, and applications...',
    'product.media': 'Product Media',
    'product.media_desc': 'Upload high-quality images of your product. First image will be the cover.',
    'product.upload_label': 'Drop images here or click to upload',
    'product.pricing': 'Pricing & MOQ',
    'product.price_placeholder': 'e.g., 12.50',
    'product.hide_price': 'Hide price (Show "On Request")',
    'product.save': 'Save Product',
    'product.enter_name_alert': 'Please enter a product name first.',
    'rfq.submit_error': 'Failed to submit RFQ. Please try again.',
    'product.loading': 'Loading products...',
    'product.no_products_desc': "You haven't added any products to your catalog yet. Start showcasing your factory's potential.",
    'product.add_first': 'Add Your First Product',
    'product.on_request': 'On Request',
    'common.confirm_delete': 'Are you sure you want to delete this item?',
    'common.units': 'Units',
    'common.filter': 'Filter',
    'common.search': 'Search...',
    'common.actions': 'Actions',
    'product.select_category': 'Select a category',
    'product.moq': 'Minimum Order Quantity',
    'profile.contact_details': 'Contact Details',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.website': 'Website',
    'profile.address': 'Address',
    'profile.capabilities': 'Capabilities',
    'profile.year_established': 'Year Established',
    'profile.employee_count': 'Employee Count',
    'profile.certifications': 'Certifications (comma separated)',
    'profile.core_capabilities': 'Core Capabilities (comma separated)',
    'profile.name_placeholder': 'Factory Name',
    'profile.desc_placeholder': 'Describe your factory and production capabilities',
    'profile.email_placeholder': 'Email address',
    'profile.phone_placeholder': 'Phone number',
    'profile.address_placeholder': 'Physical address',
    'profile.year_placeholder': 'e.g., 1995',
    'profile.employee_placeholder': 'e.g., 100-500',
    'profile.cert_placeholder': 'ISO 9001, CE, SASO...',
    'settings.title': 'Account Settings',
    'settings.subtitle': 'Manage your profile and preferences.',
    'settings.personal_info': 'Personal Info',
    'settings.business_info': 'Business Info',
    'settings.full_name': 'Full Name',
    'settings.phone_number': 'Phone Number',
    'settings.company_name': 'Company Name',
    'settings.business_type': 'Business Type',
    'settings.website': 'Website',
    'settings.address': 'Address',
    'settings.save_changes': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.success': 'Profile updated successfully!',
    'settings.error': 'Failed to update profile.',
    'settings.account_type': 'Account',
    'settings.select_type': 'Select Type',
    'settings.wholesaler': 'Wholesaler',
    'settings.contractor': 'Contractor',
    'settings.distributor': 'Distributor',
    'settings.retailer': 'Retailer',
    'settings.other': 'Other',
    'settings.phone_placeholder': '+966 5X XXX XXXX',
    'footer.desc': 'The premier B2B industrial sourcing platform connecting global buyers with certified Saudi and Gulf factories.',
    'footer.for_buyers': 'For Buyers',
    'footer.browse_products': 'Browse Products',
    'footer.find_factories': 'Find Factories',
    'footer.submit_rfq': 'Submit RFQ',
    'footer.buyer_dashboard': 'Buyer Dashboard',
    'footer.for_factories': 'For Factories',
    'footer.join_supplier': 'Join as Supplier',
    'footer.factory_dashboard': 'Factory Dashboard',
    'footer.view_rfqs': 'View RFQs',
    'footer.manage_catalog': 'Manage Catalog',
    'footer.contact': 'Contact',
    'footer.location': 'Riyadh, Saudi Arabia',
    'footer.district': 'King Abdullah Financial District',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.factories': 'المصانع',
    'nav.products': 'المنتجات',
    'nav.rfq': 'طلب تسعير',
    'nav.dashboard': 'لوحة التحكم',
    'nav.signin': 'تسجيل الدخول',
    'nav.login': 'دخول',
    'nav.messages': 'الرسائل',
    'nav.settings': 'الإعدادات',
    'nav.suppliers': 'الموردين المحفوظين',
    'nav.profile': 'ملف المصنع',
    'nav.logout': 'تسجيل الخروج',
    'nav.live': 'البث المباشر للمصنع',
    'nav.search_placeholder': 'ابحث عن منتجات أو مصانع...',
    'hero.title': 'البوابة الرقمية للتصنيع في الخليج',
    'hero.subtitle': 'تواصل مباشرة مع المصانع المعتمدة في المملكة العربية السعودية والخليج. سهّل عمليات التوريد الخاصة بك من خلال الربط المدعوم بالذكاء الاصطناعي.',
    'hero.cta.start': 'ابدأ التوريد',
    'hero.cta.factory': 'سجل مصنعك',
    'hero.cta.join': 'انضم كمصنع',
    'dashboard.welcome': 'مرحباً بك مجدداً',
    'dashboard.factory': 'لوحة تحكم المصنع',
    'dashboard.buyer': 'لوحة تحكم المشتري',
    'dashboard.stats.total_products': 'إجمالي المنتجات',
    'dashboard.stats.total_quotes': 'إجمالي عروض الأسعار',
    'dashboard.stats.profile_views': 'مشاهدات الملف الشخصي',
    'dashboard.stats.unread_messages': 'رسائل غير مقروءة',
    'dashboard.stats.active_rfqs': 'طلبات التسعير النشطة',
    'dashboard.stats.total_orders': 'إجمالي الطلبات',
    'dashboard.stats.saved_factories': 'المصانع المحفوظة',
    'dashboard.ai_insights': 'رؤى التوريد بالذكاء الاصطناعي',
    'dashboard.ai_desc': 'بناءً على اتجاهات السوق الحالية، هناك زيادة بنسبة 15٪ في الطلب على التغليف المستدام في منطقة الخليج.',
    'dashboard.ai_insights_title': 'حسّن سلسلة التوريد الخاصة بك مع ذكاء GulfFactory الاصطناعي',
    'dashboard.ai_insights_subtitle': 'رؤى التوريد بالذكاء الاصطناعي',
    'dashboard.ai_insights_description': 'بناءً على نشاطك الأخير، حددنا 3 مصانع معتمدة جديدة في المنطقة الشرقية تطابق معايير التوريد الخاصة بك للبلاستيك الصناعي.',
    'dashboard.ai_insights_button': 'عرض توصيات الذكاء الاصطناعي',
    'dashboard.performance': 'نظرة عامة على الأداء',
    'dashboard.performance_desc': 'تحليلات لآخر 30 يومًا',
    'dashboard.last_7_days': 'آخر 7 أيام',
    'dashboard.last_30_days': 'آخر 30 يومًا',
    'dashboard.last_12_months': 'آخر 12 شهرًا',
    'dashboard.views': 'مشاهدة',
    'dashboard.recent_activity': 'النشاط الأخير',
    'dashboard.no_activity': 'لا يوجد نشاط أخير',
    'dashboard.quick_actions': 'إجراءات سريعة',
    'dashboard.action.new_product': 'إضافة منتج جديد',
    'dashboard.action.view_rfqs': 'عرض طلبات التسعير',
    'dashboard.action.live_stream': 'بدء بث مباشر',
    'activity.new_rfq': 'تم استلام طلب تسعير جديد',
    'activity.new_rfq_desc': 'قطع ألمنيوم للسيارات',
    'activity.new_message': 'رسالة جديدة',
    'activity.new_message_desc': 'من شركة الصلب السعودية',
    'activity.order_completed': 'تم إكمال الطلب',
    'activity.order_completed_desc': 'طلب #ORD-742',
    
    'profile.title': 'ملف المصنع',
    'profile.subtitle': 'إدارة هوية مصنعك ومعلوماته.',
    'profile.save': 'حفظ التغييرات',
    'profile.factory_name': 'اسم المصنع',
    'profile.description': 'وصف المصنع',
    'profile.location': 'الموقع',
    'profile.category': 'الفئة الرئيسية',
    'profile.branding': 'الهوية البصرية',
    'profile.logo': 'شعار المصنع',
    'profile.banner': 'غلاف الملف الشخصي',
    'profile.basic_info': 'المعلومات الأساسية',
    
    'products.title': 'إدارة المنتجات',
    'products.subtitle': 'إدارة كتالوج المنتجات وظهورها.',
    'products.add': 'إضافة منتج',
    'products.search': 'البحث عن منتجات...',
    'products.name': 'اسم المنتج',
    'products.category': 'الفئة',
    'products.price': 'السعر',
    'products.status': 'الحالة',
    'products.actions': 'الإجراءات',
    'products.empty': 'لم يتم العثور على منتجات.',
    
    'products.new.title': 'إضافة منتج جديد',
    'products.new.subtitle': 'أدرج منتجاً جديداً في سوق GulfFactory.',
    'products.new.basic_info': 'المعلومات الأساسية',
    'products.new.media': 'وسائط المنتج',
    'products.new.description': 'الوصف',
    'products.new.min_order': 'أقل كمية للطلب',
    'products.new.price_range': 'نطاق السعر',
    'products.new.images': 'صور المنتج',
    'products.new.video': 'فيديو المنتج',
    'products.new.submit': 'إنشاء المنتج',
    'products.new.success': 'تم إنشاء المنتج بنجاح!',

    'live.title': 'البث المباشر للمصنع',
    'live.subtitle': 'بث حي من أرض المصنع لبناء الثقة مع المشترين.',
    'live.start': 'بدء البث الآن',
    'live.stop': 'إنهاء البث',
    'live.ready': 'هل أنت مستعد للبث؟',
    'live.ready_desc': 'اعرض معايير الجودة وقدرتك الإنتاجية في الوقت الفعلي.',
    'live.chat': 'الدردشة المباشرة',
    'live.no_messages': 'لا توجد رسائل بعد. ابدأ المحادثة!',
    'live.type_message': 'اكتب رسالة...',
    'live.say_something': 'اكتب استفسارك...',
    'live.ask_factory': 'اسأل المصنع مباشرة...',
    'live.host': 'المضيف',
    'live.factory': 'المصنع',
    'live.send': 'إرسال',
    'live.security': 'الأمان',
    'live.encrypted': 'مشفر بالكامل',
    'live.latency': 'التأخير',
    'live.ultra_low': 'منخفض جداً',
    'live.quality': 'الجودة',
    'live.switch_camera': 'تبديل الكاميرا',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ ما.',
    'common.success': 'تم بنجاح!',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.view_all': 'عرض الكل',
    'rfq.new_title': 'تقديم طلب تسعير جديد',
    'rfq.new_subtitle': 'قدم متطلبات مفصلة للحصول على عروض أسعار دقيقة.',
    'rfq.product_name': 'اسم المنتج / عنوان الطلب',
    'rfq.category': 'الفئة',
    'rfq.quantity': 'الكمية المطلوبة',
    'rfq.target_price': 'السعر المستهدف للوحدة (USD)',
    'rfq.description': 'المواصفات التفصيلية',
    'rfq.attachments': 'المرفقات',
    'rfq.submit': 'تقديم طلب التسعير',
    'rfq.submitting': 'جاري التقديم...',
    'rfq.success': 'تم تقديم الطلب بنجاح!',
    'rfq.success_desc': 'تم إرسال طلب عرض السعر الخاص بك إلى شبكتنا من المصانع المعتمدة.',
    'rfq.view_my': 'عرض طلباتي',
    'rfq.received_title': 'طلبات التسعير الواردة',
    'rfq.my_rfqs': 'طلبات التسعير الخاصة بي',
    'rfq.manage_desc': 'إدارة طلبات عروض الأسعار من المشترين.',
    'rfq.track_desc': 'تتبع طلبات عروض الأسعار الخاصة بك.',
    'rfq.ai_help': 'مساعد الذكاء الاصطناعي',
    'rfq.ai_write': 'اكتب لي',
    'rfq.ai_improve': 'تحسين الصياغة',
    'rfq.ai_suggest_specs': 'اقتراح مواصفات',
    'rfq.step_1': 'معلومات المنتج',
    'rfq.step_2': 'الكمية والسعر',
    'rfq.step_3': 'التفاصيل والملفات',
    'rfq.next': 'الخطوة التالية',
    'rfq.prev': 'السابق',
    'rfq.draft_saved': 'تم حفظ المسودة',
    'rfq.new_rfq': 'طلب تسعير جديد',
    'rfq.all': 'الكل',
    'rfq.pending': 'قيد الانتظار',
    'rfq.quoted': 'تم تقديم عرض',
    'rfq.accepted': 'تم القبول',
    'rfq.rejected': 'تم الرفض',
    'rfq.search_placeholder': 'البحث في طلبات التسعير...',
    'rfq.results': 'نتائج',
    'rfq.loading': 'جاري تحميل طلبات التسعير...',
    'rfq.details': 'تفاصيل الطلب',
    'rfq.status': 'الحالة',
    'rfq.date': 'التاريخ',
    'rfq.no_rfqs': 'لا توجد طلبات تسعير',
    'rfq.no_received_desc': 'لم تتلق أي طلبات تسعير بعد.',
    'rfq.no_submitted_desc': 'لم تقم بتقديم أي طلبات تسعير بعد.',
    'rfq.submit_first': 'قدم طلبك الأول الآن',
    'suppliers.title': 'الموردون المحفوظون',
    'suppliers.subtitle': 'إدارة المصانع المفضلة لديك وجهات الاتصال السريعة.',
    'suppliers.find_more': 'البحث عن المزيد',
    'suppliers.search_placeholder': 'البحث في الموردين المحفوظين...',
    'suppliers.verified': 'موثق',
    'suppliers.profile': 'الملف الشخصي',
    'suppliers.message': 'رسالة',
    'suppliers.no_suppliers': 'لا يوجد موردون محفوظون',
    'suppliers.no_suppliers_desc': 'لم تقم بحفظ أي مصانع في قائمتك بعد.',
    'suppliers.browse': 'تصفح المصانع',
    'messages.title': 'الرسائل',
    'messages.search': 'البحث في المحادثات...',
    'messages.empty': 'لا توجد رسائل بعد',
    'messages.type_placeholder': 'اكتب رسالتك...',
    'messages.select_chat': 'اختر محادثة',
    'messages.select_chat_desc': 'تواصل مع المصنعين والمشترين لمناقشة المتطلبات والعروض والجداول الزمنية للتسليم.',
    'messages.online': 'متصل',
    'messages.you': 'أنت',
    'messages.suggested_1': 'هل يمكنك إرسال المزيد من التفاصيل؟',
    'messages.suggested_2': 'ما هو وقت التسليم المتوقع؟',
    'messages.suggested_3': 'أنا مهتم بالحصول على عرض سعر.',
    'messages.upload_media': 'تحميل الوسائط',
    'messages.drop_file': 'ضع الصورة أو الفيديو هنا',
    'messages.sent_image': 'أرسل صورة',
    'messages.sent_video': 'أرسل فيديو',
    'messages.attachment': 'مرفق',
    'messages.translate': 'ترجمة',
    'messages.summary': 'ملخص الذكاء الاصطناعي',
    'messages.suggested': 'ردود مقترحة',
    'messages.convert_to_rfq': 'تحويل إلى طلب تسعير',
    'messages.last_seen': 'آخر ظهور',
    'admin.users_title': 'إدارة المستخدمين',
    'admin.users_subtitle': 'إدارة مستخدمي المنصة والأدوار والأذونات.',
    'admin.search_users': 'البحث عن المستخدمين بالاسم أو البريد الإلكتروني...',
    'admin.no_users': 'لم يتم العثور على مستخدمين',
    'admin.no_users_desc': 'لا يوجد مستخدمون حالياً في قاعدة البيانات.',
    'admin.user': 'المستخدم',
    'admin.role': 'الدور',
    'admin.joined': 'انضم في',
    'admin.actions': 'الإجراءات',
    'admin.confirm_role': 'هل أنت متأكد أنك تريد تغيير دور هذا المستخدم إلى {role}؟',
    'admin.confirm_delete': 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.',
    'admin.delete_success': 'تم حذف المستخدم بنجاح.',
    'admin.delete_error': 'فشل حذف المستخدم.',
    'admin.role_error': 'فشل تحديث دور المستخدم.',
    'admin.buyer': 'مشتري',
    'admin.factory': 'مصنع',
    'admin.admin': 'مسؤول',
    'admin.factories_title': 'إدارة المصانع',
    'admin.factories_subtitle': 'إدارة ملفات المصانع وحالة التحقق.',
    'admin.search_factories': 'البحث عن المصانع بالاسم أو البريد الإلكتروني...',
    'admin.no_factories': 'لم يتم العثور على مصانع',
    'admin.no_factories_desc': 'لا توجد مصانع مسجلة حالياً على المنصة.',
    'admin.factory_name': 'المصنع',
    'admin.location': 'الموقع',
    'admin.status': 'الحالة',
    'admin.verified': 'تم التحقق',
    'admin.pending': 'قيد التحقق',
    'admin.confirm_verify': 'هل أنت متأكد أنك تريد التحقق من هذا المصنع؟',
    'admin.confirm_revoke': 'هل أنت متأكد أنك تريد إلغاء التحقق من هذا المصنع؟',
    'admin.verify_error': 'فشل تحديث حالة التحقق من المصنع.',
    'admin.delete_factory_error': 'فشل حذف المصنع.',
    'admin.confirm_delete_factory': 'هل أنت متأكد أنك تريد حذف هذا المصنع؟ لا يمكن التراجع عن هذا الإجراء.',
    'admin.products_title': 'إدارة المنتجات',
    'admin.products_subtitle': 'مراقبة وإدارة جميع المنتجات المدرجة على المنصة.',
    'admin.search_products': 'البحث عن المنتجات بالاسم أو الفئة...',
    'admin.no_products': 'لم يتم العثور على منتجات',
    'admin.no_products_desc': 'لا توجد منتجات مدرجة حالياً على المنصة.',
    'admin.product': 'المنتج',
    'admin.factory_id': 'معرف المصنع',
    'admin.price_moq': 'السعر / الحد الأدنى للطلب',
    'admin.on_request': 'عند الطلب',
    'admin.confirm_delete_product': 'هل أنت متأكد أنك تريد حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.',
    'admin.delete_product_error': 'فشل حذف المنتج.',
    'admin.rfqs_title': 'إدارة طلبات العروض',
    'admin.rfqs_subtitle': 'مراقبة جميع طلبات العروض عبر المنصة.',
    'admin.search_rfqs': 'البحث عن طلبات العروض بالعنوان أو المعرف أو الفئة...',
    'admin.no_rfqs': 'لم يتم العثور على طلبات عروض',
    'admin.no_rfqs_desc': 'لا توجد طلبات عروض حالياً على المنصة.',
    'admin.rfq_details': 'تفاصيل طلب العرض',
    'admin.buyer_factory': 'المشتري / المصنع',
    'admin.date': 'التاريخ',
    'admin.confirm_delete_rfq': 'هل أنت متأكد أنك تريد حذف طلب العرض هذا؟ لا يمكن التراجع عن هذا الإجراء.',
    'admin.delete_rfq_error': 'فشل حذف طلب العرض.',
    'rfq.not_found': 'طلب العرض غير موجود',
    'rfq.back_to_rfqs': 'العودة إلى طلبات العروض',
    'rfq.requirements': 'المتطلبات التفصيلية',
    'rfq.attachment': 'مرفق',
    'rfq.summary': 'ملخص الطلب',
    'rfq.quantity_required': 'الكمية المطلوبة',
    'rfq.current_status': 'الحالة الحالية',
    'rfq.quotations_received': 'عروض الأسعار المستلمة',
    'rfq.quote_from_factory': 'عرض من مصنع',
    'rfq.per_unit': 'للوحدة',
    'rfq.lead_time': 'مدة التوريد',
    'rfq.additional_notes': 'ملاحظات إضافية',
    'rfq.accept_quote': 'قبول العرض',
    'rfq.reject': 'رفض',
    'rfq.no_quotes': 'لا توجد عروض أسعار مستلمة بعد',
    'rfq.no_quotes_desc': 'ستظهر عروض الأسعار هنا بمجرد تقديمها من قبل المصانع.',
    'rfq.submit_quote': 'تقديم عرض سعر',
    'rfq.price_per_unit': 'السعر للوحدة (USD) *',
    'rfq.estimated_lead_time': 'مدة التوريد المتوقعة *',
    'rfq.quote_success': 'تم تقديم عرض السعر بنجاح!',
    'rfq.quote_error': 'فشل تقديم عرض السعر.',
    'rfq.confirm_action': 'هل أنت متأكد أنك تريد {action} هذا العرض؟',
    'rfq.action_error': 'فشل {action} العرض.',
    'rfq.units': 'وحدة',
    'rfq.not_specified': 'غير محدد',
    'rfq.no_notes': 'لا توجد ملاحظات إضافية.',
    'rfq.price_placeholder': 'مثلاً: 45.00',
    'rfq.lead_time_placeholder': 'مثلاً: 14-21 يوماً',
    'rfq.notes_placeholder': 'قم بتضمين شروط الشحن، صلاحية العرض، إلخ.',
    'dashboard.loading': 'جاري التحميل...',
    'dashboard.signin_required': 'يرجى تسجيل الدخول للوصول إلى لوحة التحكم الخاصة بك',
    'dashboard.support': 'الدعم',
    'dashboard.support_desc': 'هل تحتاج إلى مساعدة في ملف تعريف المصنع الخاص بك؟',
    'dashboard.contact_agent': 'اتصل بالوكيل',
    'admin.users': 'إدارة المستخدمين',
    'admin.factories': 'إدارة المصانع',
    'admin.products': 'إدارة المنتجات',
    'admin.rfqs': 'إدارة طلبات التسعير',
    'hero.badge': 'سوق الصناعة الأول في الخليج',
    'hero.title1': 'التوريد المباشر من',
    'hero.title2': 'المصانع الموثقة',
    'hero.cta.rfq': 'أرسل طلب تسعير',
    'stats.factories': 'مصانع موثقة',
    'stats.products': 'منتجات صناعية',
    'stats.volume': 'حجم التجارة',
    'stats.countries': 'الدول التي تم الوصول إليها',
    'features.title': 'بنيت للتجارة العالمية بين الشركات',
    'features.subtitle': 'بسّط عملية الشراء الخاصة بك باستخدام أدوات مصممة خصيصاً للتوريد الصناعي وتجارة الجملة.',
    'features.v_suppliers': 'موردون موثقون',
    'features.v_suppliers_desc': 'تخضع كل مصنع لعملية تحقق صارمة. عرض الشهادات والقدرة الإنتاجية وجاهزية التصدير قبل التعامل.',
    'features.export_ready': 'جاهز للتصدير',
    'features.export_ready_desc': 'تصفية الموردين حسب شروط التجارة الدولية (EXW، FOB، CIF، DDP) والعثور على شركاء ذوي خبرة في الشحن الدولي والجمارك.',
    'features.bulk_rfq': 'سير عمل طلبات التسعير الجماعية',
    'features.bulk_rfq_desc': 'قدم طلب تسعير مفصل واحد واحصل على عروض تنافسية من العديد من المصنعين المؤهلين في وقت واحد.',
    'categories.title': 'الفئات الصناعية',
    'categories.subtitle': 'تصفح المنتجات من أفضل قطاعات التصنيع.',
    'categories.view_all': 'عرض جميع الفئات',
    'cta.ready': 'جاهز لتوسيع نطاق التوريد الخاص بك؟',
    'cta.desc': 'انضم إلى آلاف المشترين والمصانع الذين يتداولون بالفعل في سوق مصنع الخليج.',
    'cta.post_rfq': 'أرسل طلب تسعير الآن',
    'cta.create_account': 'إنشاء حساب مشتري',
    'cat.construction': 'مواد البناء',
    'cat.petrochemicals': 'البتروكيماويات',
    'cat.machinery': 'الآلات والمعدات',
    'cat.plastics': 'البلاستيك والتغليف',
    'cat.metals': 'المعادن والسبائك',
    'cat.electrical': 'المكونات الكهربائية',
    'cat.food': 'تصنيع الأغذية',
    'cat.textiles': 'المنسوجات',
    'rfq.title_placeholder': 'مثال: 5000 وحدة من عبوات HDPE المخصصة',
    'rfq.category.construction': 'مواد البناء',
    'rfq.category.petrochemicals': 'البتروكيماويات',
    'rfq.category.machinery': 'الآلات والمعدات',
    'rfq.category.plastics': 'البلاستيك والتغليف',
    'rfq.category.metals': 'المعادن والسبائك',
    'rfq.category.other': 'أخرى',
    'rfq.quantity_placeholder': 'أدخل الكمية المطلوبة',
    'rfq.desc_placeholder': 'قدم تفاصيل مثل المادة والأبعاد والشهادات المطلوبة والجدول الزمني للتسليم...',
    'product.success_title': 'تم إضافة المنتج بنجاح!',
    'product.success_desc': 'منتجك مدرج الآن في السوق ومرئي للمشترين في جميع أنحاء العالم.',
    'product.add_another': 'إضافة منتج آخر',
    'product.view_catalog': 'عرض الكتالوج',
    'product.total_products': 'إجمالي المنتجات',
    'product.product_views': 'مشاهدات المنتجات',
    'product.active_inquiries': 'استفسارات نشطة',
    'product.loading': 'جاري تحميل المنتجات...',
    'product.no_products_desc': 'لم تقم بإضافة أي منتجات إلى كتالوجك بعد. ابدأ في عرض إمكانيات مصنعك.',
    'product.add_first': 'أضف منتجك الأول',
    'product.on_request': 'عند الطلب',
    'common.confirm_delete': 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
    'common.units': 'وحدات',
    'common.filter': 'تصفية',
    'common.search': 'بحث...',
    'common.actions': 'إجراءات',
    'product.add_subtitle': 'أدرج منتجاً صناعياً جديداً في الكتالوج الخاص بك.',
    'product.select_category': 'اختر الفئة',
    'product.media': 'وسائط المنتج',
    'product.media_desc': 'قم بتحميل صور وفيديوهات عالية الجودة لعرض منتجك.',
    'product.upload_label': 'تحميل صور وفيديوهات المنتج',
    'product.pricing': 'التسعير',
    'product.hide_price': 'إخفاء السعر (طلب تسعير فقط)',
    'product.name_placeholder': 'مثال: ألواح ألمنيوم عالية الجودة',
    'product.moq_placeholder': 'مثال: 100',
    'product.desc_placeholder': 'صف ميزات المنتج، المواد، التطبيقات...',
    'product.price_placeholder': '0.00',
    'product.generating': 'جاري التوليد...',
    'product.generate_ai': 'توليد بالذكاء الاصطناعي',
    'product.moq': 'أقل كمية للطلب',
    'product.save': 'حفظ المنتج',
    'profile.contact_details': 'تفاصيل الاتصال',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'الهاتف',
    'profile.website': 'الموقع الإلكتروني',
    'profile.address': 'العنوان',
    'profile.capabilities': 'القدرات والإمكانيات',
    'profile.year_established': 'سنة التأسيس',
    'profile.employee_count': 'عدد الموظفين',
    'profile.certifications': 'الشهادات (مفصولة بفاصلة)',
    'profile.core_capabilities': 'القدرات الأساسية (مفصولة بفاصلة)',
    'profile.name_placeholder': 'اسم المصنع',
    'profile.desc_placeholder': 'صف مصنعك وقدراتك الإنتاجية',
    'profile.email_placeholder': 'عنوان البريد الإلكتروني',
    'profile.phone_placeholder': 'رقم الهاتف',
    'profile.address_placeholder': 'العنوان الفعلي',
    'profile.year_placeholder': 'مثال: 1995',
    'profile.employee_placeholder': 'مثال: 100-500',
    'profile.cert_placeholder': 'ISO 9001, CE, SASO...',
    'settings.title': 'إعدادات الحساب',
    'settings.subtitle': 'إدارة ملفك الشخصي وتفضيلاتك.',
    'settings.personal_info': 'المعلومات الشخصية',
    'settings.business_info': 'معلومات العمل',
    'settings.full_name': 'الاسم الكامل',
    'settings.phone_number': 'رقم الهاتف',
    'settings.company_name': 'اسم الشركة',
    'settings.business_type': 'نوع العمل',
    'settings.website': 'الموقع الإلكتروني',
    'settings.address': 'العنوان',
    'settings.save_changes': 'حفظ التغييرات',
    'settings.saving': 'جاري الحفظ...',
    'settings.success': 'تم تحديث الملف الشخصي بنجاح!',
    'settings.error': 'فشل تحديث الملف الشخصي.',
    'settings.account_type': 'حساب',
    'settings.select_type': 'اختر النوع',
    'settings.wholesaler': 'تاجر جملة',
    'settings.contractor': 'مقاول',
    'settings.distributor': 'موزع',
    'settings.retailer': 'تاجر تجزئة',
    'settings.other': 'آخر',
    'settings.phone_placeholder': '+966 5X XXX XXXX',
    'footer.desc': 'المنصة الرائدة لتوريد المنتجات الصناعية بين الشركات (B2B) التي تربط المشترين العالميين بالمصانع السعودية والخليجية المعتمدة.',
    'footer.for_buyers': 'للمشترين',
    'footer.browse_products': 'تصفح المنتجات',
    'footer.find_factories': 'ابحث عن مصانع',
    'footer.submit_rfq': 'تقديم طلب تسعير',
    'footer.buyer_dashboard': 'لوحة تحكم المشتري',
    'footer.for_factories': 'للمصانع',
    'footer.join_supplier': 'انضم كمورد',
    'footer.factory_dashboard': 'لوحة تحكم المصنع',
    'footer.view_rfqs': 'عرض طلبات التسعير',
    'footer.manage_catalog': 'إدارة الكتالوج',
    'footer.contact': 'اتصل بنا',
    'footer.location': 'الرياض، المملكة العربية السعودية',
    'footer.district': 'مركز الملك عبد الله المالي',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
  },
  zh: {
    'nav.home': '首页',
    'nav.factories': '工厂',
    'nav.products': '产品',
    'nav.rfq': '提交报价请求',
    'nav.dashboard': '仪表板',
    'nav.signin': '登录',
    'nav.login': '登录',
    'nav.messages': '消息',
    'nav.settings': '设置',
    'nav.suppliers': '已保存的供应商',
    'nav.profile': '工厂资料',
    'nav.logout': '注销',
    'nav.live': '现场生产',
    'nav.search_placeholder': '搜索产品或工厂...',
    'hero.title': '海湾制造业的数字门户',
    'hero.subtitle': '直接联系沙特阿拉伯和海湾合作委员会的认证工厂。通过人工智能匹配简化您的采购。',
    'hero.cta.start': '开始采购',
    'hero.cta.factory': '列出您的工厂',
    'hero.cta.join': '作为工厂加入',
    'dashboard.welcome': '欢迎回来',
    'dashboard.factory': '工厂仪表板',
    'dashboard.buyer': '买家仪表板',
    'dashboard.stats.total_products': '产品总数',
    'dashboard.stats.total_quotes': '报价总数',
    'dashboard.stats.profile_views': '资料浏览量',
    'dashboard.stats.unread_messages': '未读消息',
    'dashboard.stats.active_rfqs': '活跃的报价请求',
    'dashboard.stats.total_orders': '订单总数',
    'dashboard.stats.saved_factories': '已保存的工厂',
    'dashboard.ai_insights': '人工智能采购洞察',
    'dashboard.ai_desc': '根据当前市场趋势，海湾地区对可持续包装的需求增加了15%。',
    'dashboard.ai_insights_title': '通过 GulfFactory AI 优化您的供应链',
    'dashboard.ai_insights_subtitle': '人工智能采购洞察',
    'dashboard.ai_insights_description': '根据您近期的活动，我们在东部省份确定了 3 家符合您工业塑料采购标准的新认证工厂。',
    'dashboard.ai_insights_button': '查看 AI 建议',
    'dashboard.performance': '性能概览',
    'dashboard.performance_desc': '过去 30 天的分析',
    'dashboard.last_7_days': '过去 7 天',
    'dashboard.last_30_days': '过去 30 天',
    'dashboard.last_12_months': '过去 12 个月',
    'dashboard.views': '浏览量',
    'dashboard.recent_activity': '近期活动',
    'dashboard.no_activity': '暂无近期活动',
    'dashboard.quick_actions': '快速操作',
    'dashboard.action.new_product': '添加新产品',
    'dashboard.action.view_rfqs': '查看报价请求',
    'dashboard.action.live_stream': '上线',
    'profile.title': '工厂资料',
    'profile.subtitle': '管理您的工厂品牌和信息。',
    'profile.save': '保存更改',
    'profile.factory_name': '工厂名称',
    'profile.description': '工厂描述',
    'profile.location': '地点',
    'profile.category': '主要类别',
    'profile.branding': '品牌',
    'profile.logo': '工厂标志',
    'profile.banner': '资料横幅',
    'products.title': '产品管理',
    'products.subtitle': '管理您的产品目录和可见性。',
    'products.add': '添加产品',
    'products.search': '搜索产品...',
    'products.name': '产品名称',
    'products.category': '类别',
    'products.price': '价格',
    'products.status': '状态',
    'products.actions': '操作',
    'products.empty': '未找到产品。',
    'products.new.title': '添加新产品',
    'products.new.subtitle': '在 GulfFactory 市场上列出新产品。',
    'products.new.basic_info': '基本信息',
    'products.new.media': '产品媒体',
    'products.new.description': '描述',
    'products.new.min_order': '最小起订量',
    'products.new.price_range': '价格范围',
    'products.new.images': '产品图片',
    'products.new.video': '产品视频',
    'products.new.submit': '创建产品',
    'products.new.success': '产品创建成功！',
    'live.title': '现场生产',
    'live.subtitle': '实时直播您的工厂车间，与买家建立信任。',
    'live.start': '立即上线',
    'live.stop': '结束直播',
    'live.ready': '准备好广播了吗？',
    'live.ready_desc': '实时展示您的质量标准和生产能力。',
    'live.chat': '实时聊天',
    'live.no_messages': '暂无消息。开始对话吧！',
    'live.type_message': '输入消息...',
    'live.security': '安全',
    'live.encrypted': '端到端',
    'live.latency': '延迟',
    'live.ultra_low': '极低',
    'live.quality': '质量',
    'live.switch_camera': '切换摄像头',
    'common.loading': '加载中...',
    'common.error': '发生错误。',
    'common.success': '成功！',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.view': '查看',
    'common.view_all': '查看全部',
    'rfq.new_title': '提交新报价请求',
    'rfq.new_subtitle': '提供详细要求以获得准确报价。',
    'rfq.product_name': '产品名称 / 报价请求标题',
    'rfq.category': '类别',
    'rfq.quantity': '所需数量',
    'rfq.target_price': '目标单价 (USD)',
    'rfq.description': '详细规格',
    'rfq.attachments': '附件',
    'rfq.submit': '提交报价请求',
    'rfq.submitting': '提交中...',
    'rfq.success': '报价请求提交成功！',
    'rfq.success_desc': '您的报价请求已发送到我们的认证工厂网络。',
    'rfq.received_title': '收到的报价请求',
    'rfq.my_rfqs': '我的报价请求',
    'rfq.manage_desc': '管理来自买家的报价请求。',
    'rfq.track_desc': '跟踪您的报价请求。',
    'rfq.new_rfq': '新报价请求',
    'rfq.all': '全部',
    'rfq.pending': '待处理',
    'rfq.quoted': '已报价',
    'rfq.accepted': '已接受',
    'rfq.rejected': '已拒绝',
    'rfq.search_placeholder': '搜索报价请求...',
    'rfq.results': '结果',
    'rfq.loading': '正在加载报价请求...',
    'rfq.details': '报价请求详情',
    'rfq.status': '状态',
    'rfq.date': '日期',
    'rfq.no_rfqs': '未找到报价请求',
    'rfq.no_received_desc': '您尚未收到任何报价请求。',
    'rfq.no_submitted_desc': '您尚未提交任何报价请求。',
    'rfq.submit_first': '提交您的第一个报价请求',
    'suppliers.title': '已保存的供应商',
    'suppliers.subtitle': '管理您最喜欢的工厂和快速联系人。',
    'suppliers.find_more': '查找更多',
    'suppliers.search_placeholder': '搜索已保存的供应商...',
    'suppliers.verified': '已认证',
    'suppliers.profile': '资料',
    'suppliers.message': '消息',
    'suppliers.no_suppliers': '没有保存的供应商',
    'suppliers.no_suppliers_desc': '您尚未在列表中保存任何工厂。',
    'suppliers.browse': '浏览工厂',
    'messages.title': '消息',
    'messages.search': '搜索对话...',
    'messages.empty': '暂无消息',
    'messages.type_placeholder': '输入您的消息...',
    'messages.select_chat': '选择一个对话',
    'messages.select_chat_desc': '与制造商和买家联系，讨论需求、报价和交货时间表。',
    'messages.online': '在线',
    'messages.upload_media': '上传媒体',
    'messages.drop_file': '将图片或视频拖放到此处',
    'messages.sent_image': '发送了一张图片',
    'messages.sent_video': '发送了一个视频',
    'admin.users_title': '用户管理',
    'admin.users_subtitle': '管理平台用户、角色和权限。',
    'admin.search_users': '按姓名或电子邮件搜索用户...',
    'admin.no_users': '未找到用户',
    'admin.no_users_desc': '数据库中目前没有用户。',
    'admin.user': '用户',
    'admin.role': '角色',
    'admin.joined': '加入时间',
    'admin.actions': '操作',
    'admin.confirm_role': '您确定要将此用户的角色更改为 {role} 吗？',
    'admin.confirm_delete': '您确定要删除此用户吗？此操作无法撤销。',
    'admin.delete_success': '用户删除成功。',
    'admin.delete_error': '删除用户失败。',
    'admin.role_error': '更新用户角色失败。',
    'admin.buyer': '买家',
    'admin.factory': '工厂',
    'admin.admin': '管理员',
    'admin.factories_title': '工厂管理',
    'admin.factories_subtitle': '管理工厂资料和验证状态。',
    'admin.search_factories': '按名称或电子邮件搜索工厂...',
    'admin.no_factories': '未找到工厂',
    'admin.no_factories_desc': '目前平台上没有注册工厂。',
    'admin.factory_name': '工厂',
    'admin.location': '地点',
    'admin.status': '状态',
    'admin.verified': '已验证',
    'admin.pending': '待验证',
    'admin.confirm_verify': '您确定要验证这家工厂吗？',
    'admin.confirm_revoke': '您确定要撤销这家工厂的验证吗？',
    'admin.verify_error': '更新工厂验证状态失败。',
    'admin.delete_factory_error': '删除工厂失败。',
    'admin.confirm_delete_factory': '您确定要删除这家工厂吗？此操作无法撤销。',
    'admin.products_title': '产品管理',
    'admin.products_subtitle': '监控和管理平台上列出的所有产品。',
    'admin.search_products': '按名称或类别搜索产品...',
    'admin.no_products': '未找到产品',
    'admin.no_products_desc': '目前平台上没有列出任何产品。',
    'admin.product': '产品',
    'admin.factory_id': '工厂 ID',
    'admin.price_moq': '价格 / 最小起订量',
    'admin.on_request': '应要求提供',
    'admin.confirm_delete_product': '您确定要删除此产品吗？此操作无法撤销。',
    'admin.delete_product_error': '删除产品失败。',
    'admin.rfqs_title': '报价请求管理',
    'admin.rfqs_subtitle': '监控平台上的所有报价请求。',
    'admin.search_rfqs': '按标题、ID 或类别搜索报价请求...',
    'admin.no_rfqs': '未找到报价请求',
    'admin.no_rfqs_desc': '目前平台上没有报价请求。',
    'admin.rfq_details': '报价请求详情',
    'admin.buyer_factory': '买家 / 工厂',
    'admin.date': '日期',
    'admin.confirm_delete_rfq': '您确定要删除此报价请求吗？此操作无法撤销。',
    'admin.delete_rfq_error': '删除报价请求失败。',
    'rfq.not_found': '未找到报价请求',
    'rfq.back_to_rfqs': '返回报价请求',
    'rfq.requirements': '详细要求',
    'rfq.attachment': '附件',
    'rfq.summary': '请求摘要',
    'rfq.quantity_required': '所需数量',
    'rfq.current_status': '当前状态',
    'rfq.quotations_received': '收到的报价',
    'rfq.quote_from_factory': '来自工厂的报价',
    'rfq.per_unit': '每单位',
    'rfq.lead_time': '交货时间',
    'rfq.additional_notes': '补充说明',
    'rfq.accept_quote': '接受报价',
    'rfq.reject': '拒绝',
    'rfq.no_quotes': '尚未收到报价',
    'rfq.no_quotes_desc': '工厂提交报价后，报价将显示在此处。',
    'rfq.submit_quote': '提交报价',
    'rfq.price_per_unit': '单价 (USD) *',
    'rfq.estimated_lead_time': '预计交货时间 *',
    'rfq.quote_success': '报价提交成功！',
    'rfq.quote_error': '提交报价失败。',
    'rfq.confirm_action': '您确定要 {action} 此报价吗？',
    'rfq.action_error': '无法 {action} 报价。',
    'rfq.units': '单位',
    'rfq.not_specified': '未指定',
    'rfq.no_notes': '无补充说明。',
    'rfq.price_placeholder': '例如：45.00',
    'rfq.lead_time_placeholder': '例如：14-21 天',
    'rfq.notes_placeholder': '包括运输条款、报价有效期等。',
    'dashboard.loading': '加载中...',
    'dashboard.signin_required': '请登录以访问您的仪表板',
    'dashboard.support': '支持',
    'dashboard.support_desc': '需要工厂资料方面的帮助吗？',
    'dashboard.contact_agent': '联系代理',
    'admin.users': '管理用户',
    'admin.factories': '管理工厂',
    'admin.products': '管理产品',
    'admin.rfqs': '管理报价请求',
    'hero.badge': '海湾地区首屈一指的工业市场',
    'hero.title1': '直接采购自',
    'hero.title2': '经过认证的工厂',
    'hero.cta.rfq': '发布报价请求',
    'stats.factories': '认证工厂',
    'stats.products': '工业产品',
    'stats.volume': '贸易额',
    'stats.countries': '覆盖国家',
    'features.title': '为全球 B2B 贸易而建',
    'features.subtitle': '使用专为工业采购和批发贸易设计的工具简化您的采购流程。',
    'features.v_suppliers': '认证供应商',
    'features.v_suppliers_desc': '每家工厂都经过严格的验证过程。在参与之前查看认证、生产能力和出口准备情况。',
    'features.export_ready': '准备出口',
    'features.export_ready_desc': '按国际贸易术语（EXW、FOB、CIF、DDP）筛选供应商，并寻找在国际运输和海关方面经验丰富的合作伙伴。',
    'features.bulk_rfq': '批量报价请求工作流',
    'features.bulk_rfq_desc': '提交一份详细的报价请求，同时接收来自多家合格制造商的竞争性报价。',
    'categories.title': '工业类别',
    'categories.subtitle': '浏览顶级制造部门的产品。',
    'categories.view_all': '查看所有类别',
    'cta.ready': '准备好扩大您的采购规模了吗？',
    'cta.desc': '加入成千上万已在 GulfFactory 市场进行交易的买家和工厂。',
    'cta.post_rfq': '立即发布报价请求',
    'cta.create_account': '创建买家账户',
    'cat.construction': '建筑材料',
    'cat.petrochemicals': '石油化工',
    'cat.machinery': '机械设备',
    'cat.plastics': '塑料与包装',
    'cat.metals': '金属与合金',
    'cat.electrical': '电气组件',
    'cat.food': '食品加工',
    'cat.textiles': '纺织品',
    'product.add_subtitle': '向海湾地区经过验证的买家展示您的工业产品。',
    'product.name_placeholder': '例如：工业级 HDPE 树脂',
    'product.moq_placeholder': '例如：1000',
    'product.generating': '正在生成...',
    'product.generate_ai': '使用 AI 生成',
    'product.desc_placeholder': '描述您的产品规格、质量标准和应用...',
    'product.media': '产品媒体',
    'product.media_desc': '上传您产品的高质量图像。第一张图像将作为封面。',
    'product.upload_label': '将图像拖到此处或点击上传',
    'product.pricing': '定价与最小起订量',
    'product.price_placeholder': '例如：12.50',
    'product.hide_price': '隐藏价格（显示“按需提供”）',
    'product.save': '保存产品',
    'product.enter_name_alert': '请先输入产品名称。',
    'rfq.submit_error': '提交 RFQ 失败。请重试。',
    'product.loading': '正在加载产品...',
    'product.no_products_desc': '您尚未在目录中添加任何产品。开始展示您工厂的潜力。',
    'product.add_first': '添加您的第一个产品',
    'product.on_request': '按需提供',
    'common.confirm_delete': '您确定要删除此项吗？',
    'common.units': '单位',
    'common.filter': '筛选',
    'common.search': '搜索...',
    'common.actions': '操作',
    'settings.title': '账户设置',
    'settings.subtitle': '管理您的个人资料和偏好。',
    'settings.personal_info': '个人信息',
    'settings.business_info': '业务信息',
    'settings.full_name': '全名',
    'settings.phone_number': '电话号码',
    'settings.company_name': '公司名称',
    'settings.business_type': '业务类型',
    'settings.website': '网站',
    'settings.address': '地址',
    'settings.save_changes': '保存更改',
    'settings.saving': '保存中...',
    'settings.success': '个人资料更新成功！',
    'settings.error': '更新个人资料失败。',
    'settings.account_type': '账户',
    'settings.select_type': '选择类型',
    'settings.wholesaler': '批发商',
    'settings.contractor': '承包商',
    'settings.distributor': '分销商',
    'settings.retailer': '零售商',
    'settings.other': '其他',
    'settings.phone_placeholder': '+966 5X XXX XXXX',
    'footer.desc': '连接全球买家与沙特和海湾认证工厂的首要 B2B 工业采购平台。',
    'footer.for_buyers': '面向买家',
    'footer.browse_products': '浏览产品',
    'footer.find_factories': '寻找工厂',
    'footer.submit_rfq': '提交报价请求',
    'footer.buyer_dashboard': '买家仪表板',
    'footer.for_factories': '面向工厂',
    'footer.join_supplier': '作为供应商加入',
    'footer.factory_dashboard': '工厂仪表板',
    'footer.view_rfqs': '查看报价请求',
    'footer.manage_catalog': '管理目录',
    'footer.contact': '联系我们',
    'footer.location': '沙特阿拉伯利雅得',
    'footer.district': '阿卜杜拉国王金融区',
    'footer.rights': '版权所有。',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
  },
  ur: {
    'nav.home': 'ہوم',
    'nav.factories': 'فیکٹریاں',
    'nav.products': 'مصنوعات',
    'nav.rfq': 'RFQ جمع کروائیں',
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.signin': 'سائن ان',
    'nav.login': 'لاگ ان',
    'nav.messages': 'پیغامات',
    'nav.settings': 'ترتیبات',
    'nav.suppliers': 'محفوظ شدہ سپلائرز',
    'nav.profile': 'فیکٹری پروفائل',
    'nav.logout': 'لاگ آؤٹ',
    'nav.live': 'لائیو پروڈکشن',
    'nav.search_placeholder': 'مصنوعات یا فیکٹریاں تلاش کریں...',
    'hero.title': 'خلیجی مینوفیکچرنگ کا ڈیجیٹل گیٹ وے',
    'hero.subtitle': 'سعودی عرب اور جی سی سی میں تصدیق شدہ فیکٹریوں سے براہ راست رابطہ کریں۔ AI سے چلنے والی مماثلت کے ساتھ اپنی سورسنگ کو ہموار کریں۔',
    'hero.cta.start': 'سورسنگ شروع کریں',
    'hero.cta.factory': 'اپنی فیکٹری کی فہرست بنائیں',
    'hero.cta.join': 'بطور فیکٹری شامل ہوں',
    'dashboard.welcome': 'خوش آمدید',
    'dashboard.factory': 'فیکٹری ڈیش بورڈ',
    'dashboard.buyer': 'خریدار ڈیش بورڈ',
    'dashboard.stats.total_products': 'کل مصنوعات',
    'dashboard.stats.total_quotes': 'کل کوٹیشنز',
    'dashboard.stats.profile_views': 'پروفائل کے نظارے',
    'dashboard.stats.unread_messages': 'ان پڑھے پیغامات',
    'dashboard.stats.active_rfqs': 'فعال RFQs',
    'dashboard.stats.total_orders': 'کل آرڈرز',
    'dashboard.stats.saved_factories': 'محفوظ شدہ فیکٹریاں',
    'dashboard.ai_insights': 'AI سورسنگ بصیرت',
    'dashboard.ai_desc': 'موجودہ مارکیٹ کے رجحانات کی بنیاد پر، خلیجی خطے میں پائیدار پیکیجنگ کی مانگ میں 15 فیصد اضافہ ہوا ہے۔',
    'dashboard.ai_insights_title': 'GulfFactory AI کے ساتھ اپنی سپلائی چین کو بہتر بنائیں',
    'dashboard.ai_insights_subtitle': 'AI سورسنگ بصیرت',
    'dashboard.ai_insights_description': 'آپ کی حالیہ سرگرمی کی بنیاد پر، ہم نے مشرقی صوبے میں 3 نئی تصدیق شدہ فیکٹریاں تلاش کی ہیں جو صنعتی پلاسٹک کے لیے آپ کے سورسنگ کے معیار پر پورا اترتی ہیں۔',
    'dashboard.ai_insights_button': 'AI سفارشات دیکھیں',
    'dashboard.performance': 'کارکردگی کا جائزہ',
    'dashboard.performance_desc': 'گزشتہ 30 دنوں کے تجزیات',
    'dashboard.last_7_days': 'گزشتہ 7 دن',
    'dashboard.last_30_days': 'گزشتہ 30 دن',
    'dashboard.last_12_months': 'گزشتہ 12 ماہ',
    'dashboard.views': 'نظارے',
    'dashboard.recent_activity': 'حالیہ سرگرمی',
    'dashboard.no_activity': 'کوئی حالیہ سرگرمی نہیں',
    'dashboard.quick_actions': 'فوری اقدامات',
    'dashboard.action.new_product': 'نئی پروڈکٹ شامل کریں',
    'dashboard.action.view_rfqs': 'RFQs دیکھیں',
    'dashboard.action.live_stream': 'لائیو جائیں',
    'profile.title': 'فیکٹری پروفائل',
    'profile.subtitle': 'اپنی فیکٹری کی برانڈنگ اور معلومات کا انتظام کریں۔',
    'profile.save': 'تبدیلیاں محفوظ کریں',
    'profile.factory_name': 'فیکٹری کا نام',
    'profile.description': 'فیکٹری کی تفصیل',
    'profile.location': 'مقام',
    'profile.category': 'بنیادی زمرہ',
    'profile.branding': 'برانڈنگ',
    'profile.logo': 'فیکٹری لوگو',
    'profile.banner': 'پروفائل بینر',
    'products.title': 'مصنوعات کا انتظام',
    'products.subtitle': 'اپنی مصنوعات کے کیٹلاگ اور مرئیت کا انتظام کریں۔',
    'products.add': 'مصنوعات شامل کریں',
    'products.search': 'مصنوعات تلاش کریں...',
    'products.name': 'مصنوعات کا نام',
    'products.category': 'زمرہ',
    'products.price': 'قیمت',
    'products.status': 'حیثیت',
    'products.actions': 'اقدامات',
    'products.empty': 'کوئی مصنوعات نہیں ملیں۔',
    'products.new.title': 'نئی پروڈکٹ شامل کریں',
    'products.new.subtitle': 'GulfFactory مارکیٹ پلیس پر ایک نئی پروڈکٹ کی فہرست بنائیں۔',
    'products.new.basic_info': 'بنیادی معلومات',
    'products.new.media': 'پروڈکٹ میڈیا',
    'products.new.description': 'تفصیل',
    'products.new.min_order': 'کم از کم آرڈر کی مقدار',
    'products.new.price_range': 'قیمت کی حد',
    'products.new.images': 'مصنوعات کی تصاویر',
    'products.new.video': 'پروڈکٹ ویڈیو',
    'products.new.submit': 'پروڈکٹ بنائیں',
    'products.new.success': 'پروڈکٹ کامیابی سے بن گئی!',
    'live.title': 'لائیو پروڈکشن',
    'live.subtitle': 'خریداروں کے ساتھ اعتماد پیدا کرنے کے لیے اپنی فیکٹری کے فلور کو لائیو اسٹریم کریں۔',
    'live.start': 'ابھی لائیو جائیں',
    'live.stop': 'سٹریم ختم کریں',
    'live.ready': 'براڈکاسٹ کے لیے تیار ہیں؟',
    'live.ready_desc': 'حقیقی وقت میں اپنے معیار کے معیار اور پیداواری صلاحیت کی نمائش کریں۔',
    'live.chat': 'لائیو چیٹ',
    'live.no_messages': 'ابھی تک کوئی پیغام نہیں ہے۔ بات چیت شروع کریں!',
    'live.type_message': 'پیغام ٹائپ کریں...',
    'live.security': 'سیکیورٹی',
    'live.encrypted': 'اینڈ ٹو اینڈ',
    'live.latency': 'تاخیر',
    'live.ultra_low': 'انتہائی کم',
    'live.quality': 'معیار',
    'live.switch_camera': 'کیمرہ تبدیل کریں',
    'common.loading': 'لوڈ ہو رہا ہے...',
    'common.error': 'ایک خرابی پیش آگئی۔',
    'common.success': 'کامیابی!',
    'common.cancel': 'منسوخ کریں',
    'common.delete': 'حذف کریں',
    'common.edit': 'ترمیم کریں',
    'common.view': 'دیکھیں',
    'common.view_all': 'سب دیکھیں',
    'rfq.new_title': 'نئی RFQ جمع کروائیں',
    'rfq.new_subtitle': 'درست قیمتیں حاصل کرنے کے لیے تفصیلی ضروریات فراہم کریں۔',
    'rfq.product_name': 'پروڈکٹ کا نام / RFQ عنوان',
    'rfq.category': 'زمرہ',
    'rfq.quantity': 'مطلوبہ مقدار',
    'rfq.target_price': 'ہدف قیمت فی یونٹ (USD)',
    'rfq.description': 'تفصیلی وضاحتیں',
    'rfq.attachments': 'منسلکات',
    'rfq.submit': 'RFQ جمع کروائیں',
    'rfq.submitting': 'جمع ہو رہا ہے...',
    'rfq.success': 'RFQ کامیابی سے جمع ہو گئی!',
    'rfq.success_desc': 'آپ کی کوٹیشن کی درخواست تصدیق شدہ فیکٹریوں کے ہمارے نیٹ ورک کو بھیج دی گئی ہے۔',
    'rfq.received_title': 'موصولہ RFQs',
    'rfq.my_rfqs': 'میری RFQs',
    'rfq.manage_desc': 'خریداروں کی جانب سے کوٹیشن کی درخواستوں کا انتظام کریں۔',
    'rfq.track_desc': 'اپنی کوٹیشن کی درخواستوں کو ٹریک کریں۔',
    'rfq.new_rfq': 'نئی RFQ',
    'rfq.all': 'تمام',
    'rfq.pending': 'زیر التواء',
    'rfq.quoted': 'کوٹیشن دی گئی',
    'rfq.accepted': 'قبول کر لی گئی',
    'rfq.rejected': 'مسترد کر دی گئی',
    'rfq.search_placeholder': 'RFQs تلاش کریں...',
    'rfq.results': 'نتائج',
    'rfq.loading': 'RFQs لوڈ ہو رہی ہیں...',
    'rfq.details': 'RFQ کی تفصیلات',
    'rfq.status': 'حیثیت',
    'rfq.date': 'تاریخ',
    'rfq.no_rfqs': 'کوئی RFQs نہیں ملیں',
    'rfq.no_received_desc': 'آپ کو ابھی تک کوئی RFQs موصول نہیں ہوئی ہیں۔',
    'rfq.no_submitted_desc': 'آپ نے ابھی تک کوئی RFQs جمع نہیں کروائی ہیں۔',
    'rfq.submit_first': 'اپنی پہلی RFQ جمع کروائیں',
    'suppliers.title': 'محفوظ شدہ سپلائرز',
    'suppliers.subtitle': 'اپنی پسندیدہ فیکٹریوں اور فوری رابطوں کا انتظام کریں۔',
    'suppliers.find_more': 'مزید تلاش کریں',
    'suppliers.search_placeholder': 'محفوظ شدہ سپلائرز تلاش کریں...',
    'suppliers.verified': 'تصدیق شدہ',
    'suppliers.profile': 'پروفائل',
    'suppliers.message': 'پیغام',
    'suppliers.no_suppliers': 'کوئی محفوظ شدہ سپلائرز نہیں ہیں',
    'suppliers.no_suppliers_desc': 'آپ نے ابھی تک اپنی فہرست میں کوئی فیکٹریاں محفوظ نہیں کی ہیں۔',
    'suppliers.browse': 'فیکٹریاں براؤز کریں',
    'messages.title': 'پیغامات',
    'messages.search': 'بات چیت تلاش کریں...',
    'messages.empty': 'ابھی تک کوئی پیغام نہیں ہے',
    'messages.type_placeholder': 'اپنا پیغام ٹائپ کریں...',
    'messages.select_chat': 'بات چیت کا انتخاب کریں',
    'messages.select_chat_desc': 'ضروریات، قیمتوں اور ترسیل کے ٹائم لائنز پر بات کرنے کے لیے مینوفیکچررز اور خریداروں سے رابطہ کریں۔',
    'messages.online': 'آن لائن',
    'messages.upload_media': 'میڈیا اپ لوڈ کریں',
    'messages.drop_file': 'تصویر یا ویڈیو یہاں ڈالیں',
    'messages.sent_image': 'ایک تصویر بھیجی',
    'messages.sent_video': 'ایک ویڈیو بھیجی',
    'dashboard.loading': 'لوڈنگ ہو رہی ہے...',
    'dashboard.signin_required': 'اپنے ڈیش بورڈ تک رسائی کے لیے براہ کرم سائن ان کریں',
    'dashboard.support': 'سپورٹ',
    'dashboard.support_desc': 'اپنی فیکٹری پروفائل میں مدد کی ضرورت ہے؟',
    'dashboard.contact_agent': 'ایجنٹ سے رابطہ کریں',
    'admin.users': 'ایڈمن صارفین',
    'admin.factories': 'ایڈمن فیکٹریاں',
    'admin.products': 'ایڈمن مصنوعات',
    'admin.rfqs': 'ایڈمن RFQs',
    'hero.badge': 'خلیج کی سب سے بڑی صنعتی مارکیٹ پلیس',
    'hero.title1': 'براہ راست سورسنگ',
    'hero.title2': 'تصدیق شدہ فیکٹریوں سے',
    'hero.cta.rfq': 'RFQ پوسٹ کریں',
    'stats.factories': 'تصدیق شدہ فیکٹریاں',
    'stats.products': 'صنعتی مصنوعات',
    'stats.volume': 'تجارتی حجم',
    'stats.countries': 'ممالک تک رسائی',
    'features.title': 'عالمی B2B تجارت کے لیے بنایا گیا',
    'features.subtitle': 'صنعتی سورسنگ اور ہول سیل تجارت کے لیے خاص طور پر ڈیزائن کیے گئے ٹولز کے ساتھ اپنے خریداری کے عمل کو ہموار کریں۔',
    'features.v_suppliers': 'تصدیق شدہ سپلائرز',
    'features.v_suppliers_desc': 'ہر فیکٹری کی سخت تصدیق کی جاتی ہے۔ کام شروع کرنے سے پہلے سرٹیفیکیشنز، پیداواری صلاحیت، اور برآمدی تیاری دیکھیں۔',
    'features.export_ready': 'برآمد کے لیے تیار',
    'features.export_ready_desc': 'انکوٹرمز (EXW, FOB, CIF, DDP) کے ذریعے سپلائرز کو فلٹر کریں اور بین الاقوامی شپنگ اور کسٹمز میں تجربہ کار شراکت دار تلاش کریں۔',
    'features.bulk_rfq': 'بلک RFQ ورک فلو',
    'features.bulk_rfq_desc': 'ایک تفصیلی RFQ جمع کروائیں اور بیک وقت متعدد اہل مینوفیکچررز سے مسابقتی بولی حاصل کریں۔',
    'categories.title': 'صنعتی زمرے',
    'categories.subtitle': 'اعلیٰ مینوفیکچرنگ سیکٹرز سے مصنوعات براؤز کریں۔',
    'categories.view_all': 'تمام زمرے دیکھیں',
    'cta.ready': 'اپنی سورسنگ کو بڑھانے کے لیے تیار ہیں؟',
    'cta.desc': 'ہزاروں خریداروں اور فیکٹریوں میں شامل ہوں جو پہلے ہی گلف فیکٹری مارکیٹ پر تجارت کر رہے ہیں۔',
    'cta.post_rfq': 'ابھی RFQ پوسٹ کریں',
    'cta.create_account': 'خریدار اکاؤنٹ بنائیں',
    'cat.construction': 'تعمیراتی مواد',
    'cat.petrochemicals': 'پیٹرو کیمیکلز',
    'cat.machinery': 'مشینری اور آلات',
    'cat.plastics': 'پلاسٹک اور پیکیجنگ',
    'cat.metals': 'دھاتیں اور مرکب دھاتیں',
    'cat.electrical': 'الیکٹریکل اجزاء',
    'cat.food': 'فوڈ پروسیسنگ',
    'cat.textiles': 'ٹیکسٹائل',
    'product.add_subtitle': 'خلیج بھر میں تصدیق شدہ خریداروں کو اپنی صنعتی مصنوعات دکھائیں۔',
    'product.name_placeholder': 'مثال کے طور پر، انڈسٹریل گریڈ HDPE رال',
    'product.moq_placeholder': 'مثال کے طور پر، 1000',
    'product.generating': 'تیار ہو رہا ہے...',
    'product.generate_ai': 'AI کے ساتھ تیار کریں',
    'product.desc_placeholder': 'اپنی مصنوعات کی وضاحتیں، معیار کے معیارات اور ایپلی کیشنز بیان کریں...',
    'product.media': 'پروڈکٹ میڈیا',
    'product.media_desc': 'اپنی پروڈکٹ کی اعلیٰ معیار کی تصاویر اپ لوڈ کریں۔ پہلی تصویر کور ہوگی۔',
    'product.upload_label': 'تصاویر یہاں چھوڑیں یا اپ لوڈ کرنے کے لیے کلک کریں',
    'product.pricing': 'قیمت اور MOQ',
    'product.price_placeholder': 'مثال کے طور پر، 12.50',
    'product.hide_price': 'قیمت چھپائیں ("درخواست پر" دکھائیں)',
    'product.save': 'پروڈکٹ محفوظ کریں',
    'product.enter_name_alert': 'براہ کرم پہلے پروڈکٹ کا نام درج کریں۔',
    'rfq.submit_error': 'RFQ جمع کرانے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
    'product.loading': 'مصنوعات لوڈ ہو رہی ہیں...',
    'product.no_products_desc': 'آپ نے ابھی تک اپنے کیٹلاگ میں کوئی مصنوعات شامل نہیں کی ہیں۔ اپنی فیکٹری کی صلاحیت کو ظاہر کرنا شروع کریں۔',
    'product.add_first': 'اپنی پہلی پروڈکٹ شامل کریں',
    'product.on_request': 'درخواست پر',
    'common.confirm_delete': 'کیا آپ واقعی اس آئٹم کو حذف کرنا چاہتے ہیں؟',
    'common.units': 'یونٹس',
    'common.filter': 'فلٹر',
    'common.search': 'تلاش کریں...',
    'common.actions': 'اقدامات',
    'settings.title': 'اکاؤنٹ کی ترتیبات',
    'settings.subtitle': 'اپنے پروفائل اور ترجیحات کا انتظام کریں۔',
    'settings.personal_info': 'ذاتی معلومات',
    'settings.business_info': 'کاروباری معلومات',
    'settings.full_name': 'پورا نام',
    'settings.phone_number': 'فون نمبر',
    'settings.company_name': 'کمپنی کا نام',
    'settings.business_type': 'کاروبار کی قسم',
    'settings.website': 'ویب سائٹ',
    'settings.address': 'پتہ',
    'settings.save_changes': 'تبدیلیاں محفوظ کریں',
    'settings.saving': 'محفوظ ہو رہا ہے...',
    'settings.success': 'پروفائل کامیابی سے اپ ڈیٹ ہو گیا!',
    'settings.error': 'پروفائل اپ ڈیٹ کرنے میں ناکامی۔',
    'settings.account_type': 'اکاؤنٹ',
    'settings.select_type': 'قسم منتخب کریں',
    'settings.wholesaler': 'تھوک فروش',
    'settings.contractor': 'ٹھیکیدار',
    'settings.distributor': 'تقسیم کار',
    'settings.retailer': 'خردہ فروش',
    'settings.other': 'دیگر',
    'settings.phone_placeholder': '+966 5X XXX XXXX',
    'footer.desc': 'عالمی خریداروں کو سعودی اور خلیجی تصدیق شدہ فیکٹریوں سے جوڑنے والا سب سے بڑا B2B صنعتی سورسنگ پلیٹ فارم۔',
    'footer.for_buyers': 'خریداروں کے لیے',
    'footer.browse_products': 'مصنوعات براؤز کریں',
    'footer.find_factories': 'فیکٹریاں تلاش کریں',
    'footer.submit_rfq': 'RFQ جمع کروائیں',
    'footer.buyer_dashboard': 'خریدار ڈیش بورڈ',
    'footer.for_factories': 'فیکٹریوں کے لیے',
    'footer.join_supplier': 'بطور سپلائر شامل ہوں',
    'footer.factory_dashboard': 'فیکٹری ڈیش بورڈ',
    'footer.view_rfqs': 'RFQs دیکھیں',
    'footer.manage_catalog': 'کیٹلاگ کا انتظام کریں',
    'footer.contact': 'رابطہ کریں',
    'footer.location': 'ریاض، سعودی عرب',
    'footer.district': 'کنگ عبداللہ فنانشل ڈسٹرکٹ',
    'footer.rights': 'تمام حقوق محفوظ ہیں۔',
    'footer.privacy': 'رازداری کی پالیسی',
    'footer.terms': 'سروس کی شرائط',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (['en', 'ar', 'zh', 'ur'].includes(savedLang))) {
      setLanguage(savedLang);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    const isRTL = language === 'ar' || language === 'ur';
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    
    // Apply font classes to body
    const fontClass = language === 'ar' || language === 'ur' ? 'font-arabic' : 'font-sans';
    document.body.classList.remove('font-sans', 'font-arabic');
    document.body.classList.add(fontClass);
  }, [language]);

  const t = React.useCallback((key: string, params?: Record<string, string>) => {
    let text = translations[language]?.[key] || translations['en']?.[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(new RegExp(`{${k}}`, 'g'), v);
      });
    }
    return text;
  }, [language]);

  const dir = (language === 'ar' || language === 'ur') ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      locale: language, 
      setLocale: setLanguage, 
      t, 
      dir 
    }}>
      <div dir={dir}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
